DROP DATABASE IF EXISTS DBALUNO;
CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(20) NOT NULL
	, SEXO CHAR(1)
	, IDADE INT
	, CIDADE VARCHAR(20)
    , PRIMARY KEY (IDALUNO));
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ANDRE', 17, 'M','PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CARLOS', 21, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DIOGO', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DANIEL', 19, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EMANUEL', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('GAEL', 19, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOSE', 18, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCAS', 19, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCIANO', 20, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PATRICIA', 19, 'F', 'PALHOÇA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RAFAELLA', 21, 'F', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MALU', 22, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUZ', 19, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('HIAGO', 22, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MATHEUS', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARINA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ANANDA', 20, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EMANUELLI', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ALICIA', 21, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TALES', 18, 'M', 'TUBARAO');

SELECT * FROM ALUNO WHERE SEXO = 'M';
SELECT * FROM ALUNO WHERE IDADE = 19;

SELECT * FROM ALUNO WHERE NOME LIKE 'D%';

SELECT * FROM ALUNO WHERE (IDADE >= 20 AND IDADE <= 22);
SELECT * FROM ALUNO WHERE CIDADE IS NULL;
SELECT * FROM ALUNO WHERE CIDADE = 'Blumenau';

SELECT * FROM ALUNO WHERE IDADE <> 18;
SELECT * FROM ALUNO WHERE NOME LIKE '%ri%';

SELECT * FROM ALUNO WHERE (CIDADE = 'SÃO JOSÉ' AND SEXO = 'M' AND IDADE < 20);
SELECT * FROM ALUNO WHERE (IDADE >= 17 AND SEXO = 'M') OR (IDADE >= 20 AND SEXO = 'F') ;
SELECT * FROM ALUNO WHERE (NOME LIKE '%A%' or NOME LIKE '%R%');

SELECT NOME, IDADE FROM ALUNO WHERE SEXO = 'F';
SELECT IDALUNO, NOME FROM ALUNO WHERE CIDADE = 'BLUMENAU';
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE < 18;
SELECT NOME, CIDADE FROM ALUNO WHERE (IDADE >= 15 AND IDADE <= 18 AND CIDADE <> 'PALHOÇA');

SELECT CIDADE FROM ALUNO WHERE CIDADE IS NOT NULL;
SELECT NOME FROM ALUNO WHERE (CIDADE = 'SÃO JOSÉ' AND IDADE = 17) or (CIDADE = 'PALHOÇA' AND IDADE = 18) ;
SELECT NOME FROM ALUNO WHERE (IDADE >= 18 AND IDADE <= 25 AND CIDADE = 'TUBARÃO' AND SEXO = 'M');

SELECT NOME, IDADE FROM ALUNO ORDER BY IDADE;
SELECT IDALUNO, NOME FROM ALUNO ORDER BY NOME DESC;

SELECT * FROM ALUNO order by IDADE DESC;
SELECT * FROM ALUNO order by NOME ASC;

SELECT * FROM ALUNO order by SEXO;
SELECT * FROM ALUNO order by NOME;